### ISSUE TITLE
Preferences won't save

### ISSUE THREAD

**Issue by norristh** [exteditor/exteditor#1]
I just upgraded TB to 52.1.1 on Ubuntu 14.04.  External editor stopped working; when I used Control-E as usual, my gvim editor did not pop up, and I had to quit TB to unfreeze the window for the email I'd tried to edit.

I went into ExtEd Preferences.  No editor was set anymore.  I entered /usr/bin/gvim --nofork and tried to save, but nothing happened when I clicked Save.  I was able to Cancel out.

I uninstalled the extension, downloaded the code from this github, ran "make" and installed the resulting xpi.  With this I couldn't even get into Preferences.

I uninstalled that, and reinstalled the xpi from http://globs.org/dwnld.php?lng=en&pg=2698  Same problem I had originally; I can get into Preferences, but can't save my changes.

Let me know if you need any more information from me to troubleshoot this.  Thanks for a very useful extension!

**Comment by snipsnipsnip** [comment]
Hi, here is a (temporarily) fixed version: https://github.com/exteditor/exteditor/releases/download/v1.0.1-unofficial/exteditor_tb52_v101.xpi

**Comment by norristh** [comment]
Thanks for the super-quick response; this version works great!
