### ISSUE TITLE
Thunderbird 60 crashes when external editor closed

### ISSUE THREAD

**Issue by Hi-Angel** [exteditor/exteditor#11]
Sorry, I'm not sure if it's correct place for bugreport, or rather the Thunderbird themselves *(and whether upstream or downstream)*.

# Steps to reproduce

1. After the editor have been configured to start, press <kbd>Ctrl</kbd>+<kbd>n</kbd> to start writing new mail
2. On the "new mail" window press the button to start an external editor
3. After the editor appeared, simply close it

# Expected

You can continue interact with Thunderbird

# Actual

Thunderbird hangs for a few seconds, and then crashes.

# Additional info

For the time being I downgraded to Thunderbird-52.9.1, which works fine.

**Comment by snipsnipsnip** [comment]
Thank you for your report.
Could you locate your Crash Report ID? Mozilla people asks for them on any crash report. 
https://support.mozilla.org/en-US/kb/mozilla-crash-reporter-tb#w_viewing-crash-reports

Personally, I think Thunderbird should not crash no matter what add-ons do, but I'll implement workaround as soon as I find one.

**Comment by Hi-Angel** [comment]
Ok, sorry, for taking too long to reply.

> Could you locate your Crash Report ID? Mozilla people asks for them on >any crash report.
https://support.mozilla.org/en-US/kb/mozilla-crash-reporter-tb#w_viewing->crash-reports

I did not find `Crash Reports`, where pointed by documentation. I also tried installing the `viewabout` that they referencing to in docs, but it says it's not compatible with current Thunderbird.

However, I found one interesting thing. The crash problem I'm experiencing is on the work PC. Yesterday I tried to reproduce it on my personal laptop, but couldn't — Thunderbird says, addon `…appears to be corrupted`. I checked md5sum, and it's `c41595edb88d0bc5635ad15dfa232e87`, which matches the md5sum from my work PC.

Both computers have Archlinux installed. The only difference I see so far is that the PC with Thunderbird getting crashed have had the addon installed beforehands. After update it started complaining about incompatibility, so I installed a later release, again from the file — I wonder that made it to skip some checks. My personal laptop haven't had the addon installed.

For attempt of installation Thunderbird gives the following output:

```
1535094921972   addons.xpi      WARN    Invalid XPI: Error: Install manifest specifies unknown optionsType: 2 (resource://gre/modules/addons/XPIInstall.jsm:565:13) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:565:13
loadFromRDF@XPIInstall.jsm:838:25
loadManifestFromZipReader@XPIInstall.jsm:868:21
loadManifest@XPIInstall.jsm:1533:26
init@XPIInstall.jsm:1999:13
createLocalInstall@XPIProvider.jsm:4821:12
getInstallForFile@XPIProvider.jsm:3513:5
callProviderAsync@AddonManager.jsm:279:12
promiseCallProvider/<@AddonManager.jsm:303:53
promiseCallProvider@AddonManager.jsm:302:10
getInstallForFile/<@AddonManager.jsm:1744:29
getInstallForFile@AddonManager.jsm:1742:13
getInstallForFile@AddonManager.jsm:3453:7
doCommand/<@extensions.js:1348:13
JavaScript error: resource://gre/modules/addons/XPIInstall.jsm, line 565: Error: Install manifest specifies unknown optionsType: 2
```

> Searching...
>
>1. e-mail compose in SeaMonkey crashes - This crash report closed as 'not worth fixing.'
>2. Opening new e-mail compose window crashes with autocorrect add-on - This bug had (possibly incomplete) patches for

Well, the 2 bugreports are opened 2 and 1 year ago, so unlikely it's our case.

**Comment by insightfuls** [comment]
I'm experiencing this as well. I had no problems with TB 60 on Sierra, but when once upgrading to Mojave I see this crash. Here's a report:

https://crash-stats.mozilla.com/report/index/b02357a5-435c-4043-851b-c8fac0190218

**Comment by insightfuls** [comment]
Using the crash report as a guide I explored this a bit further.

It only happens for me if the body of the email is empty. Even a single blank line avoids this crash.

**Comment by insightfuls** [comment]
Furthermore, it only happens when you edit plain text emails, or HTML emails "as plain text".

(Emptying the HTML when editing an HTML email "as HTML" doesn't trigger this bug for me.)

**Comment by snipsnipsnip** [comment]
I have applied suggested fix (Thanks @fknorr). Let's see how it goes.

**Comment by Hi-Angel** [comment]
Thanks, the fix seems to fix it, I can't reproduce the crash anymore.

**Comment by insightfuls** [comment]
Confirmed it resolves the issue for me also. Thanks.
