### ISSUE TITLE
Preferences gone and cannot be reset

### ISSUE THREAD

**Issue by gscelsi** [exteditor/exteditor#2]
Just updated to Thunderbird 52.1.1 and the External Editor 1.0.0 preferences got lost and cannot be set since the "OK" button is not responsive. When opening the "Preferences" dialog the web console shows a "ReferenceError: nsPreferences is not defined" originating at line 70 of "chrome://exteditor/content/pref.js".

**Comment by loirotte** [comment]
The same for me! Just happy it is related to thunderbird as I've changed many things last WE on my PC. I was not sure at all... But the question is now: How can we find a quick workaround for this trouble?

**Comment by loirotte** [comment]
Oups, I've downloaded the last release, compiled it and it works again! Many thanks!

**Comment by snipsnipsnip** [comment]
@gscelsi Hi, please try [v1.0.2.](https://github.com/exteditor/exteditor/releases/download/v1.0.2/exteditor_v102.xpi)

**Comment by gscelsi** [comment]
Thank you, the new release works. 

Giuseppe

----
