### ISSUE TITLE
Cannot launch exteditor with TB 60

### ISSUE THREAD

**Issue by dbeniamine** [exteditor/exteditor#23]
## Description

Exteditor used to work, but since a few weeks, I cannot launch exteditor : nothing happens when I hit Ctrl+E or clic on "open in external editor" on the menu.

I tried:
+ Removing all my exteditor prefs and reinstalling with different version (see below)
+ Using differents external editors (`/usr/bin/gvim`, `/usr/bin/gedit`)
+ Dowgrading TB to 60.6.1

None of the above changes this behavior, however when I remove the settings I have the pop up telling me to set my editor.

## Technical information

+ OS : Debian 10 (Testing)
+ TB version 60.7.0, 60.6.1
+ exteditor version : 1.0.5-rc0, 1.0.4, 1.0.3

**Comment by cvoltz** [comment]
I have the same problem with exteditor 1.0.5 installed in Thunderbird 60.8.0 on CentOS 7.6.

**Comment by dbeniamine** [comment]
@cvoltz : I found the issue and how to fix it !

## The issue

By running the debug console I can see that the problem is in `chrome/content/exteditor.js ` line 399 :  `TypeError: document.getElementById(...) is null`
After a quick search, there should be a button in the toolbar palette that popups a menu with two options : `edit as html` and `edit as plain text`, I probably removed it as I usually don't use it (`Ctrl+E` is quicker)...

## Solution (quickfix)

Anyway right click on the palette toolbar (the bar under the menu bar) > configure, I restored the text editor button and then use the button to choose `edit as plain`.

Now I can normally use it with `Ctrl+E`.

## Long term solution

Exteditor should not fail if the button is absent, I should first look for the preference editashtml or default to false. I'll try to fix this and do a PR

**Comment by snipsnipsnip** [comment]
Thanks for the diagnostics and the patch! Will apply shortly.

**Comment by dbeniamine** [comment]
You're welcome, thanks for the quick release.

I confirm that the issue is closed for me with v106 !
