### ISSUE TITLE
External Editor preferences has no option for configuring editor command

### ISSUE THREAD

**Issue by tobiah** [exteditor/exteditor#24]
I go into the Add-ons Manager and select External Editor 1.0.5-rc0.  It gives me options for 'Automatic Updates' and that's it.  No place to configure my gvim command line. 

Thunderbird 60.3.0 (64-bit).

Thanks!

**Comment by tobiah** [comment]
I found the configuration editor off of the Add-ons menu.  Nevermind!

**Comment by JontAlle** [comment]
I installed exteditor: Go to "Tools/Add-ons Manager" and search for 
"External Editor" under "Extensions"
Then install it.  I have 1.0.3 installed.
Home page: https://github.com/exteditor/exteditor
I use Thunderbird 60.7.0 (64-bit) in linux.

To use it start an email message. To the right of the "Save" I see "Gvim"
I dont recall how I set that up. I can look in my notes how that button 
was made to appeared.
