### ISSUE TITLE
problems under Tbird 52

### ISSUE THREAD

**Issue by alan-isaac** [exteditor/exteditor#3]
snipsnipsnip offers a patch to address this problem:
https://github.com/snipsnipsnip/exteditor/commit/4d0f836e4c5b8695df3d59427bd212de234de246 
(I haven't reviewed it.)

**Comment by snipsnipsnip** [comment]
Hi, [v1.0.2](https://github.com/exteditor/exteditor/releases/download/v1.0.2/exteditor_v102.xpi) is the merged version.
