### ISSUE TITLE
Doubled-up addresses

### ISSUE THREAD

**Issue by psz2036** [exteditor/exteditor#35]
With Thunderbird 68.1.0 and exteditor 2.0.0, I see that after editing a message, some To: or CC:  addresses are "doubled up". To reproduce: start composing a message with more than a single recipient, edit message, see some addresses doubled up. Probably related (but less important) is that after editing, some addresses are near the bottom (not at top) of list of addresses in the compose window.

**Comment by snipsnipsnip** [comment]
Hi, thank you for the report with reproduction steps.
It looks like the address fields of Thunderbird 68 behaves differently from Thunderbird 60 to add-ons  . I did a workaround about it.
Can you try [v2.0.1-rc0?](https://github.com/exteditor/exteditor/releases/tag/v2.0.1-rc0)

**Comment by psz2036** [comment]
Dear Satoshi,

> It looks like the address fields of Thunderbird 68 behaves differently
> from Thunderbird 60 to add-ons . I did a workaround about it.
> Can you try v2.0.1-rc0?
> https://github.com/exteditor/exteditor/releases/tag/v2.0.1-rc0

Thanks: this seems to solve the issue.

Thanks, Paul
-- 
Paul Szabo   psz@maths.usyd.edu.au   http://www.maths.usyd.edu.au/u/psz/
School of Mathematics and Statistics   University of Sydney    Australia

**Comment by psz2036** [comment]
Dear Satoshi,

I just wrote:

   > Can you try v2.0.1-rc0?
   > https://github.com/exteditor/exteditor/releases/tag/v2.0.1-rc0
   Thanks: this seems to solve the issue.

Sorry, but now I notice... with v2.0.1-rc0, once you edit the message,
the "send" button (in the top-left of the compose window) becomes
non-operational. (As a workaround I can save to drafts, then send from
there.)

Thanks, Paul
-- 
Paul Szabo   psz@maths.usyd.edu.au   http://www.maths.usyd.edu.au/u/psz/
School of Mathematics and Statistics   University of Sydney    Australia

I support NTEU members taking a stand for workplace rights in the face of
poorly-run change management. Visit www.nteu.org.au/sydney to learn more.

**Comment by snipsnipsnip** [comment]
No problem. Thanks for confirmation :)

>Sorry, but now I notice... with v2.0.1-rc0, once you edit the message,
>the "send" button (in the top-left of the compose window) becomes
>non-operational. (As a workaround I can save to drafts, then send from
>there.)
It looks like v2.0.0 also have this problem. I'll take a look and fix as soon as I find the way.

**Comment by snipsnipsnip** [comment]
Hi, I have done another fix for the Send button issue.

Please try [v2.0.1-rc1](https://github.com/exteditor/exteditor/releases/tag/v2.0.1-rc1) if you have time and see if it works.

**Comment by psz2036** [comment]
Thanks, v201-rc1 seems to work fine.
