### ISSUE TITLE
Send button and address fields won't work sometimes after closing external editor in Thunderbird 68

### ISSUE THREAD

**Issue by snipsnipsnip** [exteditor/exteditor#39]
In #35, psz2036 noticed the issue:

>(...) with v2.0.1-rc0, once you edit the message, the "send" button (in the top-left of the compose window) becomes non-operational. (As a workaround I can save to drafts, then send from there.)

It looks like v2.0.0 also have this problem.

Workaround is either:

* As psz2036 does, save as draft and re-open the compose window before send.
* Disabling header editing in option.

**Edit:** Also address fields behaves strangely (like not responding to hitting enter) after closing external editor. Addressing widget is complaining in the error console...

**Comment by snipsnipsnip** [comment]
Released #40 as [v2.0.1-rc1](https://github.com/exteditor/exteditor/releases/tag/v2.0.1-rc1). See if it works.

**Comment by jannes-m** [comment]
Excellent fix, works again under Linux (Endeavour Arch in my case), thanks a lot!
