### ISSUE TITLE
Missing element for exteditor_editAsHtml

### ISSUE THREAD

**Issue by keestux** [exteditor/exteditor#5]
After having installed exteditor I get this error message

    JavaScript error: chrome://exteditor/content/exteditor.js, line 431: TypeError: document.getElementById(...) is null

It's in the function isEditAsHtml

    function isEditAsHtml() {
        // why is this checked attribute returned as a string rather than as a bool ???
        return (
            IsHTMLEditor() && 
            document.getElementById('exteditor_editAsHtml').getAttribute('checked') == "true"
        );
    }

**Comment by gdsowl** [comment]
You need to add the external editor toolbar element (see readme).
