### ISSUE TITLE
Editor path textbox is not shown on the option window on Thunderbird 71 beta

### ISSUE THREAD

**Issue by snipsnipsnip** [exteditor/exteditor#52]
[Cause](https://developer.thunderbird.net/add-ons/tb78/changes#less-than-textbox-greater-than)

**Comment by hase3** [comment]
Same trouble on TB 68.4.1 (OS X Mojave)

**Comment by snipsnipsnip** [comment]
Hmm, I don't have Mac so I can't reproduce. Can you try [v2.0.4-rc0?](https://github.com/exteditor/exteditor/releases/tag/v2.0.4-rc0)

**Comment by hase3** [comment]
@snipsnipsnip ,
Thank you for your reply.
I tried, but the option window doesn't appear yet. Also, I tried all of my Addon disable, and re-install the exteditor v2.0.4-rc0, not improved.
Please do not hesitate to contact me if you would like to test in Mac with my poor knowledge about Addon.

**Comment by snipsnipsnip** [comment]
Thank you for your reply too. So the option window doesn't appear at all?

I tried with my very outdated Mac (10.6) and I couldn't see any option from the usual menu (I'd say this is a bug in Thunderbird itself):

![No add-on settings found](https://user-images.githubusercontent.com/25494/73184054-27950e80-415f-11ea-81b8-8fd346dd43ce.png)

However, I could open option window from the hamburger button as a workaround:

![hamburger menu has Add-On item](https://user-images.githubusercontent.com/25494/73183264-e05a4e00-415d-11ea-8598-e6475437376d.png)
![External Editor option can be selected](https://user-images.githubusercontent.com/25494/73183274-e18b7b00-415d-11ea-8e5e-b2b180366626.png)
![Option window 
shown](https://user-images.githubusercontent.com/25494/73183335-fd8f1c80-415d-11ea-85f1-1ed4e6a91a43.png)

Does this match your experience?

**Comment by hase3** [comment]
Exactly!
I can find the option window from the hamburger button, too.
Thank you very much!

For someone who use macvim-kaoriya, following setting works fine
`/Applications/MacVim.app/Contents/bin/mvim --nofork`
