### ISSUE TITLE
Commas inside addresses create wrong split upon return from editor

### ISSUE THREAD

**Issue by brianbartholomew** [exteditor/exteditor#54]
The directory service at my university which my Thunderbird uses
returns addresses formatted like this.  Sometimes there is a space
after the comma between the last and first name:

	Bartholomew,Brian <bb@ufl.edu>

When I reply to a message and use External Editor, the address has the
same punctuation format in my external editor emacs.  But when I send
the message back to thunderbird, the address is split at the comma
between the names.  This makes the addresses wrong.  Could these
commas be quoted by External Editor for the round-trip to the editor?

My environment is:

	External Editor 2.0.2
	Thunderbird 68.2.2 (64-bit)
	GNU Emacs 25.2.2
	Ubuntu 18.04.3 LTS / bionic

**Comment by snipsnipsnip** [comment]
Hi, thank you for the report with an example. I've been reproduce
Sorry, it looks like a bug in v2.0.1. Addresses like `Bartholomew,Brian <bb@ufl.edu>`
should become `"Bartholomew,Brian" <bb@ufl.edu>` in the external editor.

Can you try [v2.0.3](https://github.com/exteditor/exteditor/releases/tag/v2.0.3)?

**Comment by brianbartholomew** [comment]
Thank you!  Version 2.0.3 fixes the quoting bug, but there is another
bug which I thought was part of the quoting bug but apparently isn't.
This other bug appeared after a Thunderbird update a few months ago.
This bug's symptom is that after the return from the external editor,
there is an additional To: line in the Thunderbird compose window with
no contents in the address field.  I don't see anything corresponding
in emacs that is suspicious, like a trailing comma in the To: line.

**Comment by snipsnipsnip** [comment]
Yes, that empty `To:` bothers me too, but I couldn't remove it without breaking the behavior. Cleaning that field from add-ons makes Send button nonfunctional. It seems like Thunderbird 68 needs that empty field to work correctly.
