### ISSUE TITLE
Recipient address delimiter

### ISSUE THREAD

**Issue by foomatic** [exteditor/exteditor#73]
Some of my contacts use a comma in their name; as in "Lastname, Firstname <user@domain>".
Since a comma is used as a delimiter for mulitple recipients by exteditor, the introduction of additional commas results in the misinterpretation of recipients when the external editor is closed. In such a case, I usually delete the additional commas manually.

Is it possible to use any other character as address delimiter, e.g. a semi-colon (";")? 
Alternatively the commas in the names could be escaped.
Would changing the delimiter break anything?

**Comment by nicoroeser** [comment]
Umm… are you sure this is not a duplicate of #54? If it is not, please explain your use case in more detail. Thanks!

**Comment by foomatic** [comment]
I had a rather old version of the extension which i updated yesterday, but by some mistake on my part, still had the old version when I tried to recreate the bug.

Everything works as intended.
Please disregard this issue.
